version: "3"
services:
  db:
    image: postgres:12
    hostname: postgresql
    container_name: api-back
    environment:
      POSTGRES_USER: pixel
      POSTGRES_PASSWORD: pixel
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: